### ISSUE TITLE
Smart indent

### ISSUE THREAD

**Issue by nddrylliog** [fasterthanlime/ooc.vim#1]
Can we has it?

**Comment by causal-agent** [comment]
I have no idea :(

**Comment by nddrylliog** [comment]
Closing this :) my fork has it now.

Btw, can we have a note on the README of this project that https://github.com/nddrylliog/ooc.vim is the preferred version now? That would probably help beginners. This project is still the top google result for 'ooc.vim'

**Comment by causal-agent** [comment]
How about I merge your fork then transfer ownership of this repo to you? (That would set up redirects from here to yours for web and git, I think)

**Comment by nddrylliog** [comment]
I'd have to delete my fork for this to work right? That seems like a good plan.

**Comment by nddrylliog** [comment]
(No irony! :) Hopefully my fork would reappear after ownership transfer)

**Comment by causal-agent** [comment]
I just merged your fork, you have to delete your repo now for me to transfer it.

**Comment by nddrylliog** [comment]
Just deleted mine, sorry for the delay.

**Comment by nddrylliog** [comment]
Thanks!
